version: '3.8'
networks:
  forum.net:
    driver: bridge

services:
  db:
    image: mysql:8.3
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-forum}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    networks:
      - forum.net
    volumes:
      - ./server/sql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - forum.net